default_install_hook_types: [pre-commit, commit-msg]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.1.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional", "@commitlint/ensure", "commitlint-plugin-function-rules"]
      args: [--config,.github/linters/commitlint.config.cjs]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args: [--line-length,'120']
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      args: [--config,.github/linters/.flake8]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--settings-path,.github/linters/.isort.cfg]
- repo: https://github.com/pycqa/pylint
  rev: v2.16.1
  hooks:
    - id: pylint
      args: [--rcfile,.github/linters/.python-lint]
- repo: https://github.com/crate-ci/typos
  rev: v1.12.12
  hooks:
    - id: typos
      args: [--config,.github/linters/.typos.toml]
