name: CI
on: [push]
jobs:
  requirements-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pip-tools
        run: |
              python -m pip install --upgrade pip
              python -m pip install --upgrade pip-tools
      - name: Check requirements
        run: |
          pip-compile --no-emit-index-url --no-header --rebuild --verbose requirements.in
          pip-compile --no-emit-index-url --no-header --rebuild --verbose requirements-dev.in
          git diff --exit-code requirements*.txt
  test:
    runs-on: ubuntu-latest
    needs: requirements-check
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Test with pytest
        run: python -m pytest
  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run pre-commit in CI
        uses: pre-commit/action@v3.0.0
      - name: Bandit Check
        run: |
          python -m pip install bandit==1.7.5
          bandit --configfile .github/linters/bandit.yml --ini .github/linters/.bandit -r .
      - name: Isort Check
        run: |
          python -m pip install flake8==6.0.0
          flake8 --configfile .github/linters/flake8.yml --ini .github/linters/.flake8 -r .
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wagoid/commitlint-github-action@v2
